package com.dogdopt.model;

import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "dogs")
public class Dog {

    @DynamoDBHashKey // maps a class property to the partition key of the table
    @DynamoDBAutoGeneratedKey
    private String dogId;

    @DynamoDBAttribute(attributeName = "name") // maps a property to a table attribute
    private String name;

    @DynamoDBAttribute(attributeName = "breed")
    private String breed;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "contactDetails")
    private Map<String, String> contactDetails;

    public String getDogId() {
        return dogId;
    }

    public String getName() {
        return name;
    }

    public String getBreed() {
        return breed;
    }

    public String getDescription() {
        return description;
    }

    public Map<String, String> getContactDetails() {
        return contactDetails;
    }

    public void setDogId(String dogId) {
        this.dogId = dogId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setContactDetails(Map<String, String> contactDetails) {
        this.contactDetails = contactDetails;
    }
}
