package com.dogdopt.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "dogs")
public class Dog {
    private String dogId;
    private String name;
    private String breed;
    private String description;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getDogId() {
        return dogId;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public String getBreed() {
        return breed;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }
}
